services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_SUPABASE_URL=${REACT_APP_SUPABASE_URL}
        - REACT_APP_SUPABASE_ANON_KEY=${REACT_APP_SUPABASE_ANON_KEY}
        - REACT_APP_TITLE=${REACT_APP_TITLE}
        - REACT_APP_VERSION=${REACT_APP_VERSION}
        - REACT_APP_API_TIMEOUT=${REACT_APP_API_TIMEOUT}
        - REACT_APP_ENABLE_NOTIFICATIONS=${REACT_APP_ENABLE_NOTIFICATIONS}
        - REACT_APP_ENABLE_SMS_NOTIFICATIONS=${REACT_APP_ENABLE_SMS_NOTIFICATIONS}
        - REACT_APP_ENABLE_DARK_MODE=${REACT_APP_ENABLE_DARK_MODE}
        - REACT_APP_DEFAULT_WAIT_TIME_PER_PERSON=${REACT_APP_DEFAULT_WAIT_TIME_PER_PERSON}
    image: cs-gecko-queue-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules   # This ensures node_modules in the container is not overwritten
    environment:
      - NODE_ENV=development
      - REACT_APP_USE_MOCK_API=${REACT_APP_USE_MOCK_API}
      - REACT_APP_SUPABASE_URL=${REACT_APP_SUPABASE_URL}
      - REACT_APP_SUPABASE_ANON_KEY=${REACT_APP_SUPABASE_ANON_KEY}
      - REACT_APP_TITLE=${REACT_APP_TITLE}
      - REACT_APP_VERSION=${REACT_APP_VERSION}
      - REACT_APP_API_TIMEOUT=${REACT_APP_API_TIMEOUT}
      - REACT_APP_ENABLE_NOTIFICATIONS=${REACT_APP_ENABLE_NOTIFICATIONS}
      - REACT_APP_ENABLE_SMS_NOTIFICATIONS=${REACT_APP_ENABLE_SMS_NOTIFICATIONS}
      - REACT_APP_ENABLE_DARK_MODE=${REACT_APP_ENABLE_DARK_MODE}
      - REACT_APP_DEFAULT_WAIT_TIME_PER_PERSON=${REACT_APP_DEFAULT_WAIT_TIME_PER_PERSON}
      - CHOKIDAR_USEPOLLING=true  # This helps with file watching in Docker
      - WDS_SOCKET_PORT=0         # This helps WebpackDevServer run correctly in Docker
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - postgres
      - supabase
    restart: unless-stopped

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./supabase/migrations:/docker-entrypoint-initdb.d
    command: ["postgres", "-c", "log_statement=all"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Supabase API
  supabase:
    image: supabase/supabase-dev:latest
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    ports:
      - "8000:8000"   # REST API
      - "9000:9000"   # Management API
    environment:
      # Database Configuration
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      
      # JWT Configuration - Important for auth
      JWT_SECRET: ${JWT_SECRET}
      ANON_KEY: ${SUPABASE_ANON_KEY}
      SERVICE_ROLE_KEY: ${SUPABASE_SERVICE_ROLE_KEY}
      
      # API Configuration
      API_EXTERNAL_URL: ${API_EXTERNAL_URL}
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_PUBLIC_URL: ${SUPABASE_PUBLIC_URL}
      STUDIO_PORT: ${STUDIO_PORT}
      
      # Disable Rate Limiting for Development
      API_RATE_LIMIT_HEADERS: ${API_RATE_LIMIT_HEADERS}
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8000/rest/v1/"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  # Nginx service for reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - frontend
      - supabase
    restart: unless-stopped

volumes:
  pgdata: 